### PR TITLE
Switching to Z-Schema

### PR DESCRIPTION
**Pull request by Santinell**
- removed tests with using strings and dates in fields minimum/maximum
- changed mechanism of "no required" (from "schema.required = [];" to "delete schema.required;")
- delete schema.required if we copy schema from param  and if required is boolean

### CODE REVIEW

**Comment by BigstickCarpet** [comment]
Hi.  Thanks for the PR.  It's much appreciated, and I'll definitely take a look at it as soon as I get a chance.  It may be a few days though, since things are super busy for me right now.

**Comment by winniehell** [comment]
This pull request includes the changes of #26. Maybe that can be split up?

**Comment by Santinell** [comment]
BigstickCarpet, where are you? We are miss you!

Looks like z-schema is not planning support of json-schema v5 in the near future.
May be better switch to ajv?

**Comment by BigstickCarpet** [comment]
I'm in India on a business trip.  working around the clock.  no time to work on code right now.  But I'll get back to it when I return to the U.S. in a couple weeks

**Comment by Santinell** [comment]
Really? a couple weeks?

**Pull request closed without merging**
