### PR TITLE
Updated the middleware to better support multiple mock swagger files

### PR DESCRIPTION
**Pull request by grouchal**
This is a replacement pull request for #28 removing unneeded files

### CODE REVIEW

**Comment by bobrafie** [comment]
how would one use this?

**Comment by grouchal** [comment]
@bobrafie this change enables the call to 

`middleware(filename, app, function (err, middleware) {...});`

to work when called multiple times with different file names.

**Comment by bobrafie** [comment]
Here's an example of how to use it with multiple swagger files:

```javascript
const myDB = new MemoryDataStore()

swaggerExpressMiddleware('swagger1.yaml', app, function(err, middleware1) {
  swaggerExpressMiddleware('swagger2.yaml', app, function(err, middleware2) {
    myDB.save(Resource.parse(mockData1), Resource.parse(mockData2), function() {
      app.use(
        middleware1.metadata(),
        middleware1.files(),
        middleware1.parseRequest(),
        middleware1.CORS(),
        middleware1.validateRequest(),
        middleware1.mock(myDB), // Use custom data store that is pre-populated with mock data
        middleware2.metadata(),
        middleware2.files(),
        middleware2.parseRequest(),
        middleware2.CORS(),
        middleware2.validateRequest(),
        middleware2.mock(myDB) // Use custom data store that is pre-populated with mock data
      )
    })

    app.use(
      bodyParser.json(), // for parsing application/json
      bodyParser.urlencoded({ extended: true }) // for parsing application/x-www-form-urlencoded
    )
  })
})

```

**Comment by simar15** [comment]
Has this been resolved?

**Comment by stephenwil** [comment]
Can this be resolved? Hitting the same issue.

**Comment by JamesMessinger** [comment]
I don't think this PR can be merged as-is anymore, because a lot of the code has changed since then.  But if someone wants to rebase this and/or submit a new PR based on the current HEAD, that would be great.

**Comment by mailtobash** [comment]
@JamesMessinger  submitted PR#153 based on the current HEAD. Could you please merge?

**Pull request closed without merging**
