### PR TITLE
bump lodash version

### PR DESCRIPTION
**Pull request by benjamine**
currently used lodash version has an identified vulnerability:
https://nodesecurity.io/advisories/577
this updates to latest version (that is patched for that vuln), and
updates usage on this lib,
luckily all breaking changes are just functions that got renamed.

they only tricky change was on test code, `_.cloneDeep` became smarter
and now produces that clone with same type (so `instanceof Resource` is
true), so I moved to use a dumber way of cloning for that test (JSON
parse+stringify).

Note this is reported on the project readme badge by david-dm
see:
image

### CODE REVIEW

**Comment by benjamine** [comment]
@BigstickCarpet bump, any ETA on getting this reviewed? security checks (like nsp, now part of npm) will likely explode on anyone using this as dependency.

**Comment by nemaniarjun** [comment]
@jamesmessinger
Hi, I plan on using this repo and can help in maintaining it for a while.

Mind taking a look at this?

**Comment by JamesMessinger** [comment]
@nemaniarjun - Yeah, my next priority is updating all the dependencies.  There are a few that aren't backwards-compatible though, so it's slightly complicated.  Nonetheless, I'll get it done very soon.   I'd be happy to accept a PR that updated some or all of the dependencies -- as long as all tests still pass.

**Comment by rkrauskopf** [comment]
@benjamine lodash has been upgraded through a separate pull request that updated additional dependencies. You can get the latest at version 1.2.0.

**Pull request closed without merging**
