### PR TITLE
OpenAPI 3 support

### PR DESCRIPTION
**Pull request by sedgewickmm18**
This is just the first step on the road to OpenAPI 3 support; however, it works for my project.
I'm opening this pull request to let you know we're working on it.

### CODE REVIEW

**Comment by JamesMessinger** [comment]
@sedgewickmm18 - Would it be possible for you to rebase this PR to the current HEAD (or close this PR and create a new one from the current HEAD)?  Right now the diff shows hundreds of files changed, which makes it really hard for me to review.

**Comment by sedgewickmm18** [comment]
Hi @JamesMessinger.
first of all my excuses for not responding in time.
I'll try to rebase the PR in the next days; it should make life, or at least enabling tests, much easier.

**Comment by sedgewickmm18** [comment]
closing this one and reopening a new one

**Comment by JamesMessinger** [comment]
**HUGE THANKS** for this PR @sedgewickmm18  🎉

**Pull request merged**
